# Generated by Django 3.2.6 on 2021-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_cart_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.TextField(),
        ),
    ]
